language: python

branches:
  only:
  - master

python:
  - "3.7"

#install:
#  - pip install -r requirements.txt
#
script:
  - ls -al
  - ls -al ebob9/
  - ls -al ebob9/travis-sandbox
  - python ebob9/travis-sandbox/test.py
